Small refactor to reduce LOC and keep code DRY.
mariocandela/beelzebub pull request #53
Opened 2023-06-21 05:43 UTC by V0idMatr1x

All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally before submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

2023-06-25 20:48 UTC, mariocandela commented on main.go
> +	// removed unnecessary fmt.Sprintf call
I really appreciate your work ❤️  I will approve it once you remove all comments

2023-06-25 20:55 UTC, mariocandela reviewed
I really appreciate your work ❤️ I will approve it once you remove all comments

2023-06-25 20:55 UTC, mariocandela commented on main.go
> +	// consolidated variables into a single declaration to reduce loc and keep DRY
```suggestion
```

2023-06-25 20:55 UTC, mariocandela commented on tracer/tracer.go
> +		// Removed redundant case breaks
```suggestion
```

2023-06-25 20:55 UTC, mariocandela commented on plugins/openai-gpt.go
>  // Reference: https://www.engraved.blog/building-a-virtual-machine-inside/
Please move up 'promptVirtualizeLinuxTerminal' declaration.

2023-06-25 20:55 UTC, mariocandela commented on main.go
> +	// removed unnecessary fmt.Sprintf call
```suggestion
```

2023-06-25 21:55 UTC, V0idMatr1x commented
> I appreciate your work ❤️ I will approve it once you remove all comments

I appreciate you letting me contribute to your project! 
Thank you for your time and the code review!

I hope to make more meaningful contributions in the future 😄

2023-06-26 06:54 UTC, mariocandela commented on plugins/openai-gpt.go
> +	promptVirtualizeLinuxTerminal = "I want you to act as a Linux terminal. I will type commands and you will reply with what the terminal should show. I want you to only reply with the terminal output
```suggestion
	// Reference: https://www.engraved.blog/building-a-virtual-machine-inside/
	promptVirtualizeLinuxTerminal = "I want you to act as a Linux terminal. I will type commands and you will reply with what the terminal should show. I want you to only reply with the terminal output inside one unique code block, and nothing else. Do no write explanations. Do not type commands unless I instruct you to do so.\n\nA:pwd\n\nQ:/home/user\n\n"
```

2023-06-26 06:58 UTC, mariocandela requested changes
For any future changes or ideas, kindly initiate a discussion on the following GitHub page: https://github.com/mariocandela/beelzebub/discussions :smile:
Thanks for your time mate

2023-06-26 07:01 UTC, V0idMatr1x commented
> For any future changes or ideas, kindly initiate a discussion on the following GitHub page: https://github.com/mariocandela/beelzebub/discussions 😄 Thanks for your time mate

Will do! You are very welcome!

2023-06-26 16:55 UTC, mariocandela approved these changes
LGTM

2023-06-26 16:55 UTC, merged